#!/bin/sh
#
#	ckiconf - Check a YAML file for indird config errors
#
Prg=`basename $0`

# check args
test "$1" || { echo "Usage: $Prg <yaml-file>" >&2; exit 1; }

# check if $1 exists
test -f "$1" || { echo "$Prg: cannot find YAML file \"$1\"" >&2; exit 2; }

# check if $1 is valid YAML
yaml2json "$1" >/dev/null || exit 3

# check if $1 is has hosts
yaml2json "$1" | jq -e -r '.hosts|keys[]' >/dev/null 2>&1 || { echo "$Prg: no '.hosts' key in $1" >&2; exit 4; }

for host in `yaml2json $1 | jq -r '.hosts|keys[]'`
do
    tmp=`mktemp /tmp/$Prg-$host.XXXXXX`
    yaml2json "$1" | jq ".hosts.$host.confs" >$tmp
    echo "------- Checking $1 host $host -------"
    for tag in `jq -r '.|keys[]' <$tmp`
    do
	INDIRD_CONF=$tmp indird $tag check
    done
    rm -f $tmp
done
