#!/bin/sh
#
#	mkiconf - Output host's indird.conf from a global YAML file
#
IndentJSON()
{
    python -c "import json, sys, collections; print json.dumps(json.load(sys.stdin, object_pairs_hook=collections.OrderedDict), separators=(',',': '), indent=$1)" | unexpand --first-only
}

Prg=`basename $0`
# check args
test "$2" || { echo "Usage: $Prg <yaml-file> <host>" >&2; exit 1; }

# check if $1 exists
test -f "$1" || { echo "$Prg: cannot find YAML file \"$1\"" >&2; exit 2; }

# check if $1 is valid YAML
yaml2json "$1" >/dev/null || exit 3

# check if $1 has hosts
yaml2json "$1" | jq -e -r '.hosts|keys[]' >/dev/null 2>&1 || { echo "$Prg: no '.hosts' key in $1" >&2; exit 4; }

# check if $2 is host in $1
yaml2json "$1" | jq -r '.hosts|keys[]' | grep "^$2\$" >/dev/null || { echo "$Prg: unknown host $2 in $1" >&2; echo "Available hosts:" >&2; yaml2json $1 | jq -r '.hosts|keys[]' | sed 's/^/    /' >&2; exit 5; }

yaml2json "$1" | jq ".hosts.$2.confs" | IndentJSON 4 | sed "1i\\
#\\
#	indird.conf for $2\\
#"
