#!/bin/bash
#
#	indirdctl - Control indird services and configuration files
#
# Legacy Todos (to be implemented and/or removed)
# - extraire les dossiers fail et montrer les fichiers qui s'y trouvent (et doivent être re-traités)
# - surveillance des logs, à définir
#
Prg=$(basename "$0")
BinDir=$(dirname "$0")
Name="${Prg%ctl}"
Indird="$BinDir/$Name"
IndPfx="$(tr '[:lower:]' '[:upper:]' <<< "$Name")_"	# Derive prefix from $Name
eval "Config=\${${IndPfx}CONFIG:-/etc/\$Name.conf}"	# Derive default file from $IndPfx/$Name
eval "CfgDir=\${${IndPfx}CFGDIR:-/etc/\$Name.d}"	# Derive default cfgdir from $IndPfx/$Name
ConfJS='config.json'
tty <&1 >/dev/null && { Bold=$(tput bold); Norm=$(tput sgr0); }

Bold() { echo "$Bold$1$Norm"; }

Usage()
{
    echo "Usage: $Prg [ status | start | stop | restart | reload | resetlog | ps ]"
    echo "       $Prg [ ls | paths | chk | nlchk | cache | split | check | debug ]"
    echo "       $Prg cache [ gen | del | chk | prt ]"
}

#   Paths command
Paths()
{
    #global Cfg Split
    local sep jqc res # Separator, jq-command, result

    test "$1" && sep="$1" || sep='|'
    jqc='add|keys_unsorted[] as $k | "\($k)'"$sep"'\(.[$k].path)"'
    res=$(cat $Cfg $Split | sed '/^#/d' | jq -sr "$jqc")
    if [ "$1" ]; then
	<<<"$res" cat
    else
	<<<"$res" column -s "$sep" -t
    fi
}

#   Split command
Split()
{
    #global Cfg Prg Config Su
    local list nb i new eql dif tag err

    test "$Cfg" || { echo "$Prg: no split possible as $Config cannot be found" >&2; exit "$ExNoAllCfg"; }
    list=$(sed '/^#/d' "$Cfg" | jq -r 'keys_unsorted[]') || exit $?
    nb=$(wc -l <<<"$list")

    new=0; eql=0; dif=0; tag=0; err=0
    for i in $list; do
	$Su "$Indird" "$i" split
	rc=$?
	case "$rc" in
	    0)		((new++));((tag++));;
	    $ExCfgEql)	((eql++));((tag++));;
	    $ExCfgDif)	((dif++));;
	    *)		((err++));;
	esac
    done
    if [[ "$nb" -gt 0 && "$tag" = "$nb" ]]; then
	echo "All $nb tags in $Config have an exact per-tag copy in $CfgDir" >&2
    else
	echo "Stats: new=$new eql=$eql new+eql=$tag dif=$dif err=$err" >&2
    fi
}

#   Check command
Check()
{
    #global List
    local stype srvs i res srv

    test "$List" || return 0
    test "$List" = 'null' && return
    for stype in "$Name" "${Name}wake"; do
	srvs=$(systemctl list-units --all | grep -v masked | grep "$stype@")
	for i in $List; do
	    srv="$stype@$i.service"
	    res=$(echo "$srvs" | grep "$srv")
	    test "$res" || echo "$srv (absent)"
	    if [[ "$res" =~ "failed" ]]; then
		echo "$srv (failed) $res"
	    elif [[ "$res" =~ "dead" && $stype == "$Name" ]]; then
		echo "$srv (dead)"
	    fi
	done
	IFS=$'\n'
	for i in $srvs; do
	    srv=$(echo "$i" | sed 's/^..//' | awk '{print $1}' | sed -E -e 's/.*@//' -e 's/\.[a-z]+$//')
	    res=$(echo "$List" | grep "$srv")
	    test "$res" || echo "$srv (non déclaré)"
	done
    done | sort -u
}

#   Debug command
Debug()
{
    #global List Cfg Split
    local tag cfg cmd vars var val

    for tag in $List; do
	cfg=$(cat $Cfg $Split | sed '/^#/d' | jq -s "add|.$tag")
	cmd=$(jq -r '.actions.copy.cmd' <<<"$cfg" | sed 's/"\$i_FILE"/$FILE/g')
	vars=$(jq -r '.env|keys_unsorted|join(" ")' <<<"$cfg")
	Bold "$tag"
	echo -e " - cmd: $cmd\n - vars: $vars"
	for var in $vars; do
	    val=$(jq -r ".env.$var" <<<"$cfg")
	    cmd=$(echo "$cmd" | sed -e "s#\$i_${var}#$val#g")
	done
	echo " - cmd calculée: $cmd"
    done
}

#
#   Main
#
# Check that we have our main script "$Name"
test -x "$Indird" || {
    Indird=$(command -v "$Name") || {
	echo "$Prg: cannot find the '$Name' script" >&2
	exit 1
    }
}

# Exit codes default values
ExCfgErr=4
ExNoAllCfg=8
ExCfgEql=9
ExCfgDif=10
# Get exit codes from the $Name script
eval $(grep '^Ex' "$Indird")

# Global config file (may not exist)
[[ -f "$Config" ]] && Cfg="$Config" || Cfg=''

# Per-tag (split) config files (may also not exist at all)
Split=$(echo $CfgDir/*/$ConfJS)	# Gather 'Split' (per stream) config files
[[ "$Split" = "$CfgDir/*/$ConfJS" ]] && Split=''

# Abort if no stream-config at all
[[ "$Cfg" || "$Split" ]] || { echo "$Prg: no global or per-tag configuration" >&2; exit "$ExCfgErr"; }

# Split instances have precedence over the same in $Cfg (through jq's 'add')
List=$(cat $Cfg $Split | sed '/^#/d' | jq -sr 'add|keys_unsorted[]')
[[ "$Dbg" ]] && { echo "$List"; exit 0; }

#   Warn about systemctl ignoring $INDIRD_CONFIG and $INDIRD_CFGDIR
[[ "$1" =~ ^(start|stop|restart|reload|resetlog)$ ]] && {
    msg="%s: ${Bold}NOTE that the '%s' variable will NOT be forwarded to systemctl$Norm\n"
    [[ "$INDIRD_CONFIG" ]] && printf "$msg" "$Prg" 'INDIRD_CONFIG' >&2
    [[ "$INDIRD_CFGDIR" ]] && printf "$msg" "$Prg" 'INDIRD_CFGDIR' >&2
}

# Prepare $Su for commands that need to write in $CfgDir
if [[ "$1" = 'cache' && "$2" =~ ^(gen|del)$ ]] || [[ "$1" = 'split' ]]; then
    [[ -w "$CfgDir" || -w "$(dirname "$CfgDir")" ]] || {
	Su='sudo'
	[[ "$INDIRD_NLOCAL" ]] && Su="$Su --preserve-env=INDIRD_NLOCAL"
    }
fi

#   Run command $1
case $1 in
    status)	for i in $List; do systemctl status "$Name@$i"; done ;;
    start|stop|restart|reload)
		for i in $List; do Bold "$i"; sudo systemctl "$1" "$Name@$i"; done ;;
    resetlog)	for i in $List; do Bold "$i"; sudo systemctl kill --signal=HUP "$Name@$i"; done ;;
    ps)		systemctl | grep "$Name@" ;;
    ls)		[[ "$List" && "$List" != 'null' ]] && {
		    echo "$List"
		    echo "$(<<<"$List" wc -l) instances" >&2
		} ;;
    chk)	for i in $List; do "$Indird" "$i" check; done ;;
    nlchk)	for i in $List; do "$Indird" "$i" nlcheck; done ;;
    cache)	for i in $List; do $Su "$Indird" "$i" cache "$2"; done ;;
    paths)	shift; Paths "$@" ;;
    split)	Split ;;
    check)	Check ;;
    debug)	Debug ;;
    *)		test "$1" = 'nlcheck' && echo "Did you mean: $Prg nlchk ?" >&2; Usage ;;
esac
