#!/bin/bash

ABS=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
mode=$1
if [ -z "$mode" ]; then mode='normal'; fi

values=$($ABS/../indirdctl check | xargs)
if [ ! -z "$values" ]; then
	echo -e "\e[1m\e[41m $values \e[0m"
else 
	if [ "$mode" == "full" ]; then echo "ok"; fi
fi