#!/bin/bash

Prg=$(basename "$0")
ExCfgErr=4

#   Output all Conf paths in $2 (or top) separated by $1 (or space)
ConfPaths()
{
    #global Conf
    local sep idx key path

    test "$2" && { sep="${1- }"; idx="$2._keys"; } || { sep=''; idx="_keys"; }
    if [ -v Conf["$idx"] ]; then
	echo -n "$sep$idx"
	for key in ${Conf[$idx]}; do
	    test "$2" && path="$2.$key" || path="$key"
	    ConfPaths "${1- }" "$path"
	done
    elif [ "$2" ]; then
	echo -n "$sep$2"
    fi
}

#   Pretty print cache in "$1"
PrettyCache()
{
    local beg val paths

    # Minimal check
    beg='declare -A Conf='
    [[ "$1" =~ ^$beg ]] || { echo "$Prg: cache data does not start with '$beg'" >&2; exit $ExCfgErr; }

    val="$1"
    # We source "$1" in a local variable, to not alter the global one
    source <(<<<"$val" sed '1s/^declare /local /')
    paths=$(ConfPaths '|')
    test "$Dbg" && echo "nbl=$(<<<"$val" wc -l) paths=\"$paths\"" >&2
    #echo "Paths=\"${!Conf[@]}\"" >&2
    mapfile -n2 <<<"$val"
    [[ "${#MAPFILE[@]}" -gt 1 ]] || {
	test "$Dbg" && echo "Mono (${#MAPFILE[@]} line)" >&2
	val=$(<<<"$val" sed -r 's/( \[[_a-z])/\n \1/g; s/=\(\[/=(\n  [/; s/" \)$/"\n)/')
    }
    # We use awk below to be sure to keep the valid bash-escaped values
    echo "$beg("
    <<<"$val" sed -nr "s/^  \[([^]]+)]=(.*)$/\1|\2/p" | awk -F'|' -f <(cat <<-\EOF
	BEGIN { split(ARGV[1],p); ARGC = 1 }
	{ a[$1] = $2 }
	END { for (i in p) { printf("  [%s]=%s\n", p[i], a[p[i]]) } }
EOF
    ) "$paths"
    echo ")"
}

if [ "$1" ]; then
    if [ "$1" = '-' ]; then
	Cnf=$(cat)
    elif [ -s "$1" ]; then
	Cnf=$(<"$1")
    else
	echo "Usage: $0 declare-p-output-file"
	exit 1
    fi
else
    Cnf=$(cat)
fi
if [ "$Dbg" ]; then
    # We want to check that global Conf is not affected by PrettyCache
    set -e -C
    oConf='cache_vali'
    test -s "$f" && source "$f"
fi
PrettyCache "$Cnf"
if [[ "$Dbg" && -s "$oConf" ]]; then
    PrettyCache "$(declare -p Conf)" >v
    PrettyCache "$(<cache_vali)" >V
fi
