---

- name: debug filename
  tags: ['subconf']
  debug:
    var: item.path

- name: create dirs in server
  tags: ['subconf']
  file:
    state: directory
    path: "/etc/indird.d/{{flowname}}"
  become: true
  delegate_to: "{{server}}"
  when: inventory_hostname == server


- name: deploy conf files
  copy:
    src: "{{item.path}}"
    dest: "/etc/indird.d/{{flowname}}/config.json"
    owner: root
    group: root
    mode: '0644'
  become: true
  delegate_to: "{{server}}"
  when: inventory_hostname == server