---

- name: debug filename
  tags: ['subconf']
  debug:
    var: item

- name: create dirs in server
  tags: ['subconf']
  file:
    state: directory
    path: "/etc/indird.d/{{flowname}}"
  become: true
  delegate_to: "{{server}}"
  when: inventory_hostname == server


# - name: deploy conf files
#   copy:
#     src: "{{ tmpconffolder }}{{item.path | basename}}"