---

- name: debug filename
  tags: ['reconf', 'subconf']
  debug:
    var: item.path

- name: create dirs in server
  tags: ['reconf', 'subconf']
  file:
    state: directory
    path: "/etc/indird.d/{{flowname}}"
  become: true
  delegate_to: "{{server}}"
  when: inventory_hostname == server


- name: check conf files
  tags: ['reconf', 'subconf']
  stat:
    path: "{{ item.path }}"
  register: conf_stat
  delegate_to: localhost


- name: deploy conf files
  tags: ['reconf', 'subconf']
  copy:
    src: "{{item.path}}"
    dest: "/etc/indird.d/{{flowname}}/config.json"
    owner: root
    group: root
    mode: '0644'
  become: true
  when: 
    - inventory_hostname == server
    - conf_stat.stat.size > 0