#!/bin/bash
#
#	ckiconf - Check a YAML file for indird config errors
#
Prg=`basename $0`

# check args
test "$1" && yaml="$1" || { echo "Usage: $Prg <yaml-file>" >&2; exit 1; }

# check if $yaml exists
test -f "$yaml" || { echo "$Prg: cannot find YAML file \"$yaml\"" >&2; exit 2; }

# check if $yaml is valid YAML
conf=$(yaml2json "$yaml") || exit 3

# check if $conf has hosts
keys=$(<<<"$conf" jq -e -r '.hosts|keys_unsorted[]' 2>/dev/null) || { echo "$Prg: no '.hosts' key in $yaml" >&2; exit 4; }
keys=$(<<<"$keys" grep -v '^macros$')

for host in $keys
do
    #	Extract $host config
    hcfg=$(<<<"$conf" jq ".hosts.$host.confs" | tee out/$host)
    test "$hcfg" = 'null' && { echo "$Prg: cannot find '.hosts.$host.confs' in \"$yaml\"" >&2; continue; }
    #	Check each tag in $conf
    echo "======= Checking host $host in $yaml ======="
    for tag in $(<<<"$hcfg" jq -r 'keys_unsorted[]' | grep -v '^macros$')
    do
    echo "------- Checking $tag on host $host -------"
	<<<"$hcfg" jq ".$tag" | INDIRD_CONFIG=- INDIRD_NLOCAL=y indird $tag check	# use non-local check mode
    done
done
