---

- hosts: localhost
  connection: local
  tags: ['local', 'reconf', 'always']
  gather_facts: true

  tasks:
    - name: test des binaires nécessaires
      command: "which {{ item }}"
      changed_when: false
      failed_when: installed.rc not in [0]
      register: installed
      with_items: 
        - jq
        - yaml2json


    - name: test des chemins nécessaires
      stat:
        path: "{{ item }}"
      with_items: 
        - "{{ path_repo_infra_data_misc }}"
        - "{{ path_repo_base }}"
      register: path_exists

    - name: assertion sur les chemins nécessaires
      assert: 
        that: "{{ item.stat.exists }}"
        fail_msg: "{{ item.item }} manquant"
        quiet: yes
      with_items: "{{ path_exists.results }}"


    - file:
        path: "{{ tmpconffile }}"
        state: directory

    # - name: extraction configuration
    #   shell: "yaml2json {{ path_repo_infra_data_misc }}/indird.yml | jq .hosts.{{ item }}.confs > {{ tmpconffile }}{{ item }}"
    #   changed_when: False
    #   with_items: 
    #     - procom1
    #     - profntd1
    #     - profnte1
    #     - prefnt2
    #     - profntj1
    #     - profntr1
    #     - profnts1
    #   register: out
    # #- debug: var=out
    # - name: copy procom1 conf for satcom1
    #   copy: 
    #     src: "{{tmpconffile}}procom1"
    #     dest: "{{tmpconffile}}{{item}}"
    #   loop:
    #     - "satcom1"
 
# intéressant mais ça casse tout l'ordre donc à voir plus tard
    - name: Extraction configuration en pur Ansible
      vars:
        hosts_list:
          - procom1
          - profntd1
          - profnte1
          - prefnt2
          - profntj1
          - profntr1
          - profnts1


      block:
        - name: Charger le YAML complet
          ansible.builtin.slurp:
            src: "{{ path_repo_infra_data_misc }}/indird.yml"
          register: indird_yaml_raw

        - name: Convertir YAML en dict Ansible
          set_fact:
            indird_data: "{{ indird_yaml_raw.content | b64decode | from_yaml }}"

        - name: Écrire chaque conf en JSON
          ansible.builtin.copy:
            dest: "{{ tmpconffile }}{{ item }}"
            content: "{{ indird_data.hosts[item].confs | to_nice_json }}"
          loop: "{{ hosts_list }}"

        - name: copy procom1 conf for satcom1
          copy: 
            src: "{{tmpconffile}}procom1"
            dest: "{{tmpconffile}}{{item}}"
          loop:
            - "satcom1"
 
        - name: fetch running conf
          shell:
            cmd: "scp {{ item }}:/etc/indird.conf {{ runconffile }}{{item}}"
          loop:
            - satcom1
            - profntd1
            - profnte1
            - prefnt2
            - profntj1
            - profntr1
            - profnts1  


        - name: compare with prod
          shell:
            cmd: "diff -u <(jq --sort-keys . {{tmpconffile}}{{item}}) <(jq --sort-keys . {{ runconffile }}{{item}}) > /tmp/diff_indird_{{item}}"
          loop:
            - satcom1
            - profntd1
            - profnte1
            - prefnt2
            - profntj1
            - profntr1
            - profnts1  
          args:
            executable: /bin/bash
          register: diff_results
        #   changed_when: false
          failed_when: diff_results.rc > 1
          changed_when: diff_results.rc == 1    

        - name: debug diff_results  
          debug: 
            var: diff_results

       
        - name: Affichage des différences trouvées
          shell: 
            cmd: "cat /tmp/diff_indird_{{item}}"
          loop: 
            - satcom1
            - profntd1
            - profnte1
            - prefnt2
            - profntj1
            - profntr1
            - profnts1  
#          when: diff_results.results.rc == 1
          changed_when: false


#TODO: duplication entre items de "extraction configuration" et hosts du playbook suivant (idée, on génère pour tous les serveurs)

- hosts: satcom1 profntd1 profnte1 prefnt2 profntj1 profntr1 profnts1 #procom1 procom3
  gather_facts: True

  vars:
    conffile: /etc/indird.conf
    srcdir: "{{ playbook_dir }}/../indird"
    bindir: /usr/local/bin
    systemddir: /etc/systemd/system
    chgscript: { changed: false }
  
  tasks:
    - name: gestion paramètre
      tags: ['reconf', 'install']
      set_fact:
        filterprocess: "{{ filter | default('') }}"

    - name: dépot bash-static
      tags: ['install']
      copy:
        src: files/bash-static
        dest: /bin/bash-static
        mode: 0755
      become: true

    - name: dépot script indird
      tags: ['install']
      copy: 
        src: "{{ srcdir }}/indird"
        dest: "{{ bindir }}"
        mode: 0755
      become: True
      register: chgscript

    - name: dépot scripts de contrôle et de rsync supervisés
      tags: ['scripts']
      copy: 
        src: "files/{{ item }}"
        dest: "{{ bindir }}"
        mode: 0755
      become: True
      with_items: ['indirdctl', 'indird_rsync.sh']

    - name: dépot sonde norme
      tags: ['scripts']
      copy: 
        src: "files/normed_{{ item }}"
        dest: "{{ bindir }}/norme.d/{{ item }}"
        mode: 0755
      become: True
      with_items: ['indird.sh', 'indird_broken_in.sh']

    - name: dépot sonde state
      tags: ['scripts']
      copy: 
        src: "files/stated_indird"
        dest: "{{ bindir }}/state.d/indird"
        mode: 0755
      become: True

    - name: dépot configuration
      tags: ['reconf']
      copy:
        src: "{{ tmpconffile }}{{ ansible_hostname }}"
        dest: "{{ conffile }}"
        mode: 0644
      become: True
      register: chgconf

    - name: dépot services
      tags: ['install']
      copy: 
        src: "{{ srcdir }}/{{ item }}"
        dest: "{{ systemddir }}"
        mode: 0644
      with_items: 
        - 'indird@.service'
        - 'indirdwake@.service'
        - 'indirdwake@.path'
      become: True

    - name: setup service indird
      tags: ['install']
      service:
        name: indird@{}
        enabled: False
        state: stopped
      become: True

    - name: lister les services
      tags: ['reconf', 'install']
      shell: "cat {{ conffile }} | jq -r 'keys|.[]' | grep '{{ filterprocess }}'; exit 0"
      register: services
      changed_when: False

    - name: mode reload
      tags: ['reconf']
      set_fact:
        state: reloaded
      when: chgconf.changed == true
    - name: mode restart
      tags: ['install']
      set_fact:
        state: restarted
      when: chgscript.changed == true

    - name: setup services indird@service
      tags: ['reconf', 'install']
      service:
        name: "indird@{{ item }}"
        enabled: False
        state: "{{ state }}"
      with_items: "{{ services.stdout_lines }}"
      become: True
      when: services is not skipped and state is defined

    - name: dépot logrotate
      tags: ['logrotate', 'install']
      copy:
        src: "files/logrotate_indird"
        dest: "/etc/logrotate.d/indird"
        mode: 0644
      become: True
