---

# playbook dédié au déploiement progressif de la solution sur procom3 (ou tout autre suivant)

- hosts: procom3
  gather_facts: True

  vars:
    conffile: /etc/indird.conf
    srcdir: "{{ playbook_dir }}/../indird"
    bindir: /usr/local/bin
    systemddir: /etc/systemd/system
    chgscript: { changed: false }
  
  tasks:
    - name: gestion paramètre
      tags: ['reconf', 'install', 'procom3']
      set_fact:
        filterprocess: "{{ filter | default('') }}"

    # - name: dépot bash-static
    #   tags: ['install', 'procom3']
    #   copy:
    #     src: files/bash-static
    #     dest: /bin/bash-static
    #     mode: 0755
    #   become: true

    - name: dépot script indird
      tags: ['install', 'procom3']
      copy: 
        src: "{{ srcdir }}/indird"
        dest: "{{ bindir }}"
        mode: 0755
      become: True
      register: chgscript

    - name: dépot script de contrôle
      tags: ['scripts', 'procom3']
      copy: 
        src: "files/indirdctl"
        dest: "{{ bindir }}"
        mode: 0755
      become: True

    - name: dépot sonde norme
      tags: ['scripts', 'procom3']
      copy: 
        src: "files/normed_indird.sh"
        dest: "{{ bindir }}/norme.d/indird.sh"
        mode: 0755
      become: True

    - name: dépot sonde state
      tags: ['scripts', 'procom3']
      copy: 
        src: "files/stated_indird"
        dest: "{{ bindir }}/state.d/indird"
        mode: 0755
      become: True

    - name: dépot configuration
      tags: ['reconf', 'procom3']
      copy:
        src: "{{ tmpconffile }}{{ ansible_hostname }}"
        dest: "{{ conffile }}"
        mode: 0644
      become: True
      register: chgconf

    - name: dépot services
      tags: ['install', 'procom3']
      copy: 
        src: "{{ srcdir }}/{{ item }}"
        dest: "{{ systemddir }}"
        mode: 0644
      with_items: 
        - 'indird@.service'
        - 'indirdwake@.service'
        - 'indirdwake@.path'
      become: True

    - name: setup service indird
      tags: ['install', 'procom3']
      service:
        name: indird@{}
        enabled: False
        state: stopped
      become: True

    - name: lister les services
      tags: ['reconf', 'install', 'procom3']
      shell: "cat {{ conffile }} | jq -r 'keys|.[]' | grep '{{ filterprocess }}'; exit 0"
      register: services
      changed_when: False

    - name: mode reload
      tags: ['reconf']
      set_fact:
        state: reloaded
      when: chgconf.changed == true
    - name: mode restart
      tags: ['install', 'procom3']
      set_fact:
        state: restarted
      when: chgscript.changed == true

    - name: setup services indird@service
      tags: ['reconf', 'install', 'procom3']
      service:
        name: "indird@{{ item }}"
        enabled: False
        state: "{{ state }}"
      with_items: "{{ services.stdout_lines }}"
      become: True
      when: services is not skipped and state is defined

    - name: dépot logrotate
      tags: ['logrotate', 'install', 'procom3']
      copy:
        src: "files/logrotate_indird"
        dest: "/etc/logrotate.d/indird"
        mode: 0644
      become: True
