---

- hosts: g_source
  gather_facts: false

  vars:
    - users: &users ['lad_test', 'lad_test_mhu']
    - directories: ['KU/RP', 'GED']

  tasks:

    - user:
        name: "{{ item }}"
        shell: '/usr/bin/mysecureshell'
        home: '/space/home/{{ item }}'
      with_items: "{{ users }}"
      become: true

    - name: Sets authorized_key for user on com node ({{ inventory_hostname }})
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', 'files/{{ item }}.authorized_keys') }}" 
      with_items: "{{ users }}"
      become: true

    - name: création dossiers lad_test*
      file: 
        path: '/space/home/{{ item.0 }}/{{ item.1 }}'
        state: directory
        owner: '{{ item.0 }}'
        recurse: yes
      loop: "{{ users|product(directories)|list }}"
      become: true

- hosts: prefnt2
  gather_facts: false

  vars:
    - users: *users

  tasks: 

    - name: dirs pour KU
      file: 
        path: '/space/applisdata/esisdoccu/LAD_RP/{{ item }}'
        state: directory
        owner: www-data
        group: www-data
        mode: '0775'
      with_items: '{{ users }}'
      become: true
      become_user: www-data

    - name: liens pour KU
      file: 
        src: '/space/applisdata/esisdoccu/LAD_RP/{{ item }}'
        dest: '/space/home/lad_lsyncd_preprod/{{ item }}'
        owner: www-data
        group: www-data
        state: link
        mode: '0775'
      with_items: '{{ users }}'
      become: true
      become_user: lad_lsyncd_preprod

    - name: dir pour GED
      file: 
        path: '{{ item }}'
        state: directory
        owner: www-data
        group: www-data
        mode: '0775'
      with_items: 
        - '/space/applisdata/esisdoccu/GED/lad_test'
        - '/space/applisdata/esisdoccu/GED/geddoccu_test'
      become: true
      become_user: www-data

    - name: liens pour KU
      file: 
        src: '/space/applisdata/esisdoccu/GED/geddoccu_test'
        dest: '/space/home/lad_lsyncd_preprod/GED'
        owner: www-data
        group: www-data
        state: link
        mode: '0775'
      become: true
      become_user: lad_lsyncd_preprod